# Generated by Django 5.2.13 on 2026-07-23 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_alter_todolist_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalhesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('todo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalhe', to='Todo.todolist')),
            ],
        ),
    ]
