# Generated by Django 5.2.13 on 2026-07-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0003_detalheslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalheslist',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10),
        ),
    ]
