# Generated by Django 5.2.13 on 2026-07-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0004_detalheslist_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalheslist',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
